name: pushImage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    CONTAINER_REGISTRY: docker.io
    CONTAINER_NAME: hack22image
    DEPLOYMENT_MANIFEST_PATH: |
        ./deploy.yml
        ./secret.yml
        ./cm.yaml
jobs:
    buildImage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Checkout Code
            
            - name: Login to image repository
              uses: docker/login-action@v2
              with:
                registry: ${{ env.CONTAINER_REGISTRY }}
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build docker image
              run: |
                docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}

            - name: Push the image
              run: |
                docker push ${{ secrets.DOCKER_USER }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
